---
- hosts: all
  # sudo permission
  become: true

  vars:
    tomcat8_folder: bin
    tomcat8_path: "/root/tomcat8/apache-tomcat8-8.5.34/{{ tomcat8_folder }}"
    grep_string: "[/]root/tomcat8/apache-tomcat8-8.5.34/{{ tomcat8_folder }}"
  tasks:
    - name: Copying the war file to the destination
      copy: src=/root/myweb/myweb-0.12.0.war dest="{{ tomcat8_path }}/../webapps/"

    - name: ==> shutdown qle tomcat8 ,path = "{{ tomcat8_path }}/bin/"
      command: sh {{ tomcat8_path }}/shutdown.sh

    - name: ==> sleep 3s
      command: sleep 3s

    - name: Check if Apache is running
      shell: ps aux | grep '{{ grep_string }}' | awk '{print $2}'
      ignore_errors: yes
      changed_when: false
      register: service_apache_status

    - debug: msg="Check if Apache is running {{ service_apache_status }}"
    - debug: msg="service_apache_status.stdout != '' =  {{ service_apache_status.stdout != ''}}"

    - name: kill process is tomcat8 is still running
      shell: kill $(ps aux | grep '{{ grep_string }}' | awk '{print $2}')
      when: service_apache_status.stdout != ''

    - command: sleep 1s
      when: service_apache_status.stdout != ''

    - name: ==> startup qle tomcat8 , path = {{ tomcat8_path }}/bin/startup.sh
      shell: setsid /bin/sh -i -c "{{ tomcat8_path }}/startup.sh"
